#!/usr/bin/env python3
"""Build Strategy E's core 400-stock universe and maintain dynamic Chartink symbols.

The official Nifty MidSmallcap 400 constituent CSV is the core source. Any valid
NSE/Kite symbol seen in a Chartink webhook can be enrolled dynamically even when
it is outside the core universe.
"""
import argparse, csv, json, urllib.request
from pathlib import Path
from config import DATA_DIR

NIFTY_MIDSMALLCAP400_URL = "https://www.niftyindices.com/IndexConstituent/ind_niftymidsmallcap400list.csv"
CORE_FILE = DATA_DIR / "universe" / "nifty_midsmallcap400.csv"
DYNAMIC_FILE = DATA_DIR / "universe" / "dynamic_chartink_symbols.txt"
COMBINED_FILE = DATA_DIR / "universe" / "feature_universe.txt"


def download_core(url=NIFTY_MIDSMALLCAP400_URL):
    req=urllib.request.Request(url,headers={"User-Agent":"Mozilla/5.0 StrategyE/7"})
    with urllib.request.urlopen(req,timeout=30) as r:
        data=r.read().decode("utf-8-sig",errors="replace")
    rows=list(csv.DictReader(data.splitlines()))
    symbols=[]
    for row in rows:
        s=(row.get("Symbol") or row.get("symbol") or row.get("Tradingsymbol") or row.get("tradingsymbol") or "").strip().upper()
        if s and s not in symbols: symbols.append(s)
    if len(symbols)<350: raise RuntimeError(f"Unexpected constituent response: only {len(symbols)} symbols")
    CORE_FILE.parent.mkdir(parents=True,exist_ok=True)
    with CORE_FILE.open("w",encoding="utf-8",newline="") as f:
        f.write("symbol,source\n")
        for s in symbols: f.write(f"{s},NIFTY_MIDSMALLCAP400\n")
    return symbols


def read_core():
    if not CORE_FILE.exists(): return []
    with CORE_FILE.open(encoding="utf-8-sig",newline="") as f:
        return [(r.get("symbol") or r.get("Symbol") or "").strip().upper() for r in csv.DictReader(f) if (r.get("symbol") or r.get("Symbol"))]


def read_dynamic():
    if not DYNAMIC_FILE.exists(): return []
    return [x.strip().upper() for x in DYNAMIC_FILE.read_text(encoding="utf-8").splitlines() if x.strip() and not x.startswith("#")]


def rebuild_combined(include_nifty50=True):
    core=read_core(); dyn=read_dynamic(); symbols=list(dict.fromkeys(( ["NIFTY 50"] if include_nifty50 else [] ) + core + dyn))
    COMBINED_FILE.parent.mkdir(parents=True,exist_ok=True); COMBINED_FILE.write_text("# Auto-generated by Strategy E universe manager\n"+"\n".join(symbols)+"\n",encoding="utf-8")
    return symbols




def validate_symbol(symbol):
    """Validate a symbol against the cached NSE instruments list. Read-only."""
    s=str(symbol).strip().upper()
    if not s:
        return False, "EMPTY_SYMBOL"
    try:
        from kite_client import KiteBroker
        row=KiteBroker().instrument(s)
        return True, row.get("tradingsymbol", s)
    except Exception as exc:
        return False, str(exc)


def enroll_file(path):
    """Validate and enroll symbols from a text file, returning per-symbol results."""
    syms=[x.strip().upper() for x in Path(path).read_text(encoding="utf-8").splitlines() if x.strip() and not x.lstrip().startswith("#")]
    syms=list(dict.fromkeys(syms))
    results=[]
    from kite_client import KiteBroker
    broker=KiteBroker()
    instruments=broker.instruments()
    for s in syms:
        row=instruments.get(s)
        if not row:
            results.append({"symbol":s,"status":"REJECTED","reason":"NSE_INSTRUMENT_NOT_FOUND"})
            continue
        enroll(s)
        results.append({"symbol":s,"status":"ENROLLED"})
    combined=rebuild_combined()
    return {"requested":len(syms),"enrolled":sum(r["status"]=="ENROLLED" for r in results),"rejected":sum(r["status"]!="ENROLLED" for r in results),"results":results,"combined_count":len(combined)}


def enroll(symbol):
    s=str(symbol).strip().upper()
    if not s: return
    core=set(read_core()); dyn=read_dynamic()
    if s not in core and s not in dyn:
        DYNAMIC_FILE.parent.mkdir(parents=True,exist_ok=True)
        with DYNAMIC_FILE.open("a",encoding="utf-8") as f: f.write(s+"\n")
    rebuild_combined()


def main():
    p=argparse.ArgumentParser();p.add_argument("action",choices=["sync","enroll"]);p.add_argument("symbols",nargs="*");p.add_argument("--url",default=NIFTY_MIDSMALLCAP400_URL)
    a=p.parse_args()
    if a.action=="sync":
        syms=download_core(a.url); combined=rebuild_combined(); print(json.dumps({"core_count":len(syms),"combined_count":len(combined),"core_file":str(CORE_FILE),"combined_file":str(COMBINED_FILE)},indent=2)); return
    for s in a.symbols: enroll(s)
    print(json.dumps({"core_count":len(read_core()),"dynamic_count":len(read_dynamic()),"combined_count":len(rebuild_combined())},indent=2))

if __name__=='__main__': main()
